### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by SimonSoftware** [andrazznidar/bbb-player#9]
On Docker installation:
when i execute: 
`python3 bbb-player.py --combine xxxxx`

i have this error

`Traceback (most recent call last):
  File "bbb-player.py", line 395, in <module>
    ffmpegCombine('mp4', fileName=fileName)
  File "bbb-player.py", line 51, in ffmpegCombine
    ffmpeg.run(output)
  File "/usr/local/lib/python3.7/site-packages/ffmpeg/_run.py", line 320, in run
    overwrite_output=overwrite_output,
  File "/usr/local/lib/python3.7/site-packages/ffmpeg/_run.py", line 285, in run_async
    args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'`

then if i install ffmpeg
`pip install ffmpeg`

i have this one

`Traceback (most recent call last):
  File "bbb-player.py", line 395, in <module>
    ffmpegCombine('mp4', fileName=fileName)
  File "bbb-player.py", line 44, in ffmpegCombine
    video_file = ffmpeg.input('./deskshare/deskshare.' + suffix)
AttributeError: module 'ffmpeg' has no attribute 'input'`

**Comment by SimonSoftware** [comment]
I've tried a fresh install on ubuntu 20.04 without docker: the --combine start but i have a blank video, only voices in background. My files are in mp4 format as deskshare.mp4 and webcams.mp4

**Comment by andrazznidar** [comment]
Hi @SimonSoftware!
Thanks for the bug report. The issue with ffmpeg in Docker has been resolved. You can download the latest version with `docker pull andrazznidar/bbb-player` and then run the container normally `docker run -p 5000:5000 -v /path/to/your/folder/myBBBmeetings:/app/downloadedMeetings andrazznidar/bbb-player`



Could you please check which of your two files (deskshare.mp4 or webcams.mp4) has the video?
Currently the `--combine` function only combines video in deskshare with audio in webcams.

**Comment by andrazznidar** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
